plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tareq.floatingtasbih'
    compileSdk 35

    defaultConfig {
        applicationId "com.tareq.floatingtasbih"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "5.0-beta"
    }
}

dependencies {
}
